{ config, pkgs, ... }:
  {
  # The systemd service generated by NixOS doesn't handle resume from suspend
  # properly; this one will
  systemd.services.vpn-client = {
    description = "OpenVPN client";
    wantedBy = [];
    after = [ "Network.target" ];
    path = [ pkgs.iptables pkgs.iproute pkgs.nettools ];
    serviceConfig.ExecStart = "@${pkgs.openvpn}/sbin/openvpn openvpn --suppress-timestamps --config /run/secrets/client.ovpn";
    serviceConfig.Restart = "always";
    serviceConfig.Type = "notify";
  };

  age.secrets."client.ovpn".file = ../secrets/client.ovpn.age;
  age.secrets."vpn-auth".file = ../secrets/vpn-auth.age;
}
